# Generated by Django 2.2.1 on 2019-05-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
